[package]
name = "xx-resource-parser"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.4"
log = "0.4"
simplelog = "0.8"
anyhow = "1.0"
structopt = "0.3"
